"""Write real MCAP recordings from NPA run artifacts for the Foxglove viewer.

NPA runs publish frames (`.png` / `.jpg` / `.ppm` …), JSON metrics, and text logs
to object storage. Foxglove reads MCAP, so this module packs those existing
artifacts into a genuine MCAP file using Foxglove's well-known JSON schemas:

- ``foxglove.CompressedImage`` on ``/camera/<name>`` — renders in the Image panel
- ``foxglove.Log`` on ``/log`` — renders in the Log panel
- ``npa.RunMetrics`` on ``/metrics/<name>`` — numeric fields plot in the Plot panel

Honesty rules baked in:

- Nothing is synthesized. Only artifacts that exist on disk become messages.
- NPA run artifacts usually carry no per-frame capture time, so frame timestamps
  are generated from an explicit ``--fps`` clock. That is recorded both in the
  MCAP ``metadata`` record and in the returned summary
  (``timestamps="synthetic-fps"``) so no consumer mistakes it for sensor time.

Requires the optional ``mcap`` dependency (``pip install "npa[foxglove]"``); the
import error is turned into an actionable message rather than a stack trace.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

from npa.workbench.lichtblick import compressed_image_message

NS_PER_S = 1_000_000_000

# Browser/Foxglove-native compressed image formats.
_DIRECT_IMAGE_FORMATS = {
    ".png": "png",
    ".jpg": "jpeg",
    ".jpeg": "jpeg",
    ".webp": "webp",
    ".avif": "avif",
}
# Images Foxglove cannot decode directly; transcoded to PNG with Pillow.
_TRANSCODE_IMAGE_SUFFIXES = {".ppm", ".pgm", ".pbm", ".pnm", ".bmp", ".tif", ".tiff"}
_LOG_SUFFIXES = {".log", ".txt"}
_METRIC_SUFFIXES = {".json"}

_TOPIC_UNSAFE_RE = re.compile(r"[^A-Za-z0-9_./-]+")

_TIME_SCHEMA: dict[str, Any] = {
    "type": "object",
    "title": "time",
    "properties": {
        "sec": {"type": "integer", "minimum": 0},
        "nsec": {"type": "integer", "minimum": 0, "maximum": 999_999_999},
    },
}

COMPRESSED_IMAGE_SCHEMA: dict[str, Any] = {
    "$comment": "Generated by NPA from foxglove.CompressedImage",
    "title": "foxglove.CompressedImage",
    "description": "A compressed image",
    "type": "object",
    "properties": {
        "timestamp": dict(_TIME_SCHEMA, description="Timestamp of image"),
        "frame_id": {
            "type": "string",
            "description": "Frame of reference for the image.",
        },
        "data": {
            "type": "string",
            "contentEncoding": "base64",
            "description": "Compressed image data",
        },
        "format": {
            "type": "string",
            "description": "Image format (e.g. png, jpeg, webp)",
        },
    },
}

LOG_SCHEMA: dict[str, Any] = {
    "$comment": "Generated by NPA from foxglove.Log",
    "title": "foxglove.Log",
    "description": "A log message",
    "type": "object",
    "properties": {
        "timestamp": dict(_TIME_SCHEMA, description="Timestamp of log message"),
        "level": {
            "title": "LogLevel",
            "description": "Log level",
            "oneOf": [
                {"title": "UNKNOWN", "const": 0},
                {"title": "DEBUG", "const": 1},
                {"title": "INFO", "const": 2},
                {"title": "WARNING", "const": 3},
                {"title": "ERROR", "const": 4},
                {"title": "FATAL", "const": 5},
            ],
        },
        "message": {"type": "string", "description": "Log message"},
        "name": {"type": "string", "description": "Process or node name"},
        "file": {"type": "string", "description": "Filename"},
        "line": {"type": "integer", "minimum": 0, "description": "Line number in the file"},
    },
}

LOG_LEVELS = {"unknown": 0, "debug": 1, "info": 2, "warning": 3, "error": 4, "fatal": 5}


class McapWriteError(RuntimeError):
    """Raised when an MCAP recording cannot be produced."""


@dataclass(frozen=True)
class FrameInput:
    """One image artifact destined for a ``foxglove.CompressedImage`` channel."""

    path: Path
    camera: str = "camera"
    timestamp_ns: int | None = None


@dataclass(frozen=True)
class LogInput:
    """One text artifact destined for the ``foxglove.Log`` channel."""

    path: Path
    name: str = "log"
    level: str = "info"


@dataclass(frozen=True)
class MetricsInput:
    """One JSON artifact destined for a metrics channel."""

    path: Path
    name: str = "metrics"


@dataclass
class McapSummary:
    """What was actually written (used by CLI output and the agent API)."""

    output: str = ""
    size_bytes: int = 0
    message_count: int = 0
    channels: dict[str, int] = field(default_factory=dict)
    frames: int = 0
    logs: int = 0
    metrics: int = 0
    skipped: list[str] = field(default_factory=list)
    start_time_ns: int = 0
    end_time_ns: int = 0
    timestamps: str = ""
    fps: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "output": self.output,
            "size_bytes": self.size_bytes,
            "message_count": self.message_count,
            "channels": dict(self.channels),
            "frames": self.frames,
            "logs": self.logs,
            "metrics": self.metrics,
            "skipped": list(self.skipped),
            "start_time_ns": self.start_time_ns,
            "end_time_ns": self.end_time_ns,
            "timestamps": self.timestamps,
            "fps": self.fps,
        }


def _require_mcap():
    try:
        from mcap.writer import Writer  # noqa: PLC0415
    except ModuleNotFoundError as exc:  # pragma: no cover - exercised via monkeypatch
        raise McapWriteError(
            "MCAP support requires the optional 'mcap' dependency. "
            'Install it with: pip install "npa[foxglove]"'
        ) from exc
    return Writer


def safe_topic(name: str, *, prefix: str) -> str:
    """Return a stable, safe Foxglove topic for an artifact name."""
    token = _TOPIC_UNSAFE_RE.sub("_", str(name or "").strip().strip("/"))
    token = token.strip("_") or "default"
    base = str(prefix or "").rstrip("/")
    return f"{base}/{token}" if base else f"/{token}"


def _time_fields(timestamp_ns: int) -> dict[str, int]:
    ts = max(0, int(timestamp_ns))
    return {"sec": ts // NS_PER_S, "nsec": ts % NS_PER_S}


# Cheap content checks so a mislabeled/corrupt file is skipped with a reason
# instead of being shipped to the viewer as an undecodable "image".
_IMAGE_MAGIC: dict[str, tuple[bytes, ...]] = {
    "png": (b"\x89PNG\r\n\x1a\n",),
    "jpeg": (b"\xff\xd8\xff",),
}
# Container formats whose magic lives after a 4-byte length/size prefix:
# WebP is "RIFF" + size + "WEBP"; AVIF is size + "ftyp" + a brand.
_IMAGE_CONTAINER_MAGIC: dict[str, tuple[bytes, bytes]] = {
    "webp": (b"RIFF", b"WEBP"),
    "avif": (b"", b"ftyp"),
}


def _image_magic_ok(payload: bytes, image_format: str) -> bool:
    prefixes = _IMAGE_MAGIC.get(image_format)
    if prefixes:
        return any(payload.startswith(prefix) for prefix in prefixes)
    container = _IMAGE_CONTAINER_MAGIC.get(image_format)
    if container:
        head, tag = container
        if head and not payload.startswith(head):
            return False
        return payload[8:12] == tag if tag == b"WEBP" else payload[4:8] == tag
    return True


def _read_image(path: Path) -> tuple[bytes, str] | None:
    """Return ``(payload, format)`` for an image artifact, or None if unsupported.

    Encoding is delegated to :func:`npa.workbench.lichtblick.encode_frame_to_compressed_bytes`
    — the same encoder the Lichtblick MCAP writer uses — so both viewers are fed
    byte-identical frames and there is one place that decides PNG vs JPEG vs
    transcode. Obvious corruption is rejected here before it reaches a viewer.
    """
    suffix = path.suffix.lower()
    if suffix not in _DIRECT_IMAGE_FORMATS and suffix not in _TRANSCODE_IMAGE_SUFFIXES:
        return None
    if suffix in _DIRECT_IMAGE_FORMATS and not _image_magic_ok(
        path.read_bytes()[:16], _DIRECT_IMAGE_FORMATS[suffix]
    ):
        return None
    from npa.workbench.lichtblick import encode_frame_to_compressed_bytes  # noqa: PLC0415

    try:
        return encode_frame_to_compressed_bytes(str(path))
    except Exception:  # noqa: BLE001 - unreadable/corrupt frame, reported as skipped
        return None


def _metric_schema(payload: dict[str, Any], title: str) -> dict[str, Any]:
    properties: dict[str, Any] = {"timestamp": dict(_TIME_SCHEMA)}
    for key, value in payload.items():
        if isinstance(value, bool):
            properties[key] = {"type": "boolean"}
        elif isinstance(value, (int, float)):
            properties[key] = {"type": "number"}
        elif isinstance(value, str):
            properties[key] = {"type": "string"}
        # Nested structures are serialized as strings so the schema stays flat
        # and the Plot panel can address every numeric field directly.
        else:
            properties[key] = {"type": "string"}
    return {"title": title, "type": "object", "properties": properties}


def _flatten_metric_payload(payload: dict[str, Any]) -> dict[str, Any]:
    flat: dict[str, Any] = {}
    for key, value in payload.items():
        # "timestamp" is reserved for the message time struct; a payload field of
        # the same name would be silently overwritten (and unplottable).
        if key == "timestamp":
            key = "timestamp_value"
        if isinstance(value, (bool, int, float, str)) or value is None:
            flat[key] = value
        else:
            flat[key] = json.dumps(value)[:2000]
    return flat


def collect_run_inputs(
    input_path: str | Path,
    *,
    max_frames: int = 0,
) -> tuple[list[FrameInput], list[MetricsInput], list[LogInput], list[str]]:
    """Discover convertible artifacts under a run directory.

    Camera names come from the parent directory (``.../camera/front/0001.png`` →
    ``front``), so multi-camera runs land on separate Foxglove topics.
    """
    root = Path(str(input_path or "")).expanduser()
    if not root.is_dir():
        raise McapWriteError(f"input path is not a directory: {root}")

    frames: list[FrameInput] = []
    metrics: list[MetricsInput] = []
    logs: list[LogInput] = []
    skipped: list[str] = []

    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        suffix = path.suffix.lower()
        relative = path.relative_to(root).as_posix()
        if suffix in _DIRECT_IMAGE_FORMATS or suffix in _TRANSCODE_IMAGE_SUFFIXES:
            parent = path.parent.name if path.parent != root else "camera"
            frames.append(FrameInput(path=path, camera=parent or "camera"))
        elif suffix in _METRIC_SUFFIXES:
            metrics.append(MetricsInput(path=path, name=path.stem))
        elif suffix in _LOG_SUFFIXES:
            logs.append(LogInput(path=path, name=path.stem))
        else:
            skipped.append(relative)

    if max_frames and len(frames) > max_frames:
        frames = frames[: int(max_frames)]
    return frames, metrics, logs, skipped


def write_run_mcap(
    *,
    output: str | Path,
    frames: Iterable[FrameInput] = (),
    metrics: Iterable[MetricsInput] = (),
    logs: Iterable[LogInput] = (),
    fps: float = 10.0,
    start_time_ns: int = 0,
    run_id: str = "",
    camera_topic_prefix: str = "/camera",
    metrics_topic_prefix: str = "/metrics",
) -> McapSummary:
    """Write an MCAP recording from real run artifacts and return a summary."""
    Writer = _require_mcap()

    frame_list = list(frames)
    metric_list = list(metrics)
    log_list = list(logs)
    if not (frame_list or metric_list or log_list):
        raise McapWriteError(
            "nothing to convert: no image, metrics, or log artifacts were provided"
        )

    rate = float(fps) if float(fps) > 0 else 10.0
    step_ns = int(NS_PER_S / rate)
    base_ns = int(start_time_ns) if int(start_time_ns) > 0 else _default_start_ns(
        frame_list, metric_list, log_list
    )

    summary = McapSummary(
        output=str(output),
        timestamps="synthetic-fps",
        fps=rate,
    )

    target = Path(str(output)).expanduser()
    target.parent.mkdir(parents=True, exist_ok=True)

    with target.open("wb") as handle:
        writer = Writer(handle)
        writer.start(profile="", library="npa-foxglove-mcap")

        image_schema_id = writer.register_schema(
            name="foxglove.CompressedImage",
            encoding="jsonschema",
            data=json.dumps(COMPRESSED_IMAGE_SCHEMA).encode("utf-8"),
        )
        log_schema_id: int | None = None
        camera_channels: dict[str, int] = {}
        metric_channels: dict[str, int] = {}
        log_channel_id: int | None = None
        first_ns = 0
        last_ns = 0

        for index, frame in enumerate(frame_list):
            try:
                loaded = _read_image(frame.path)
            except OSError as exc:
                summary.skipped.append(f"{frame.path.name}: {exc}")
                continue
            if loaded is None:
                summary.skipped.append(f"{frame.path.name}: unsupported image format")
                continue
            payload, image_format = loaded
            topic = safe_topic(frame.camera, prefix=camera_topic_prefix)
            if topic not in camera_channels:
                camera_channels[topic] = writer.register_channel(
                    topic=topic, message_encoding="json", schema_id=image_schema_id
                )
            timestamp_ns = (
                int(frame.timestamp_ns)
                if frame.timestamp_ns is not None
                else base_ns + index * step_ns
            )
            # Shared message builder: identical wire shape to the Lichtblick writer.
            message: dict[str, Any] = compressed_image_message(
                payload, fmt=image_format, stamp_ns=timestamp_ns, frame_id=frame.camera
            )
            writer.add_message(
                channel_id=camera_channels[topic],
                log_time=timestamp_ns,
                data=json.dumps(message).encode("utf-8"),
                publish_time=timestamp_ns,
                sequence=index,
            )
            summary.frames += 1
            summary.channels[topic] = summary.channels.get(topic, 0) + 1
            first_ns = timestamp_ns if not first_ns else min(first_ns, timestamp_ns)
            last_ns = max(last_ns, timestamp_ns)

        for index, metric in enumerate(metric_list):
            try:
                raw = json.loads(metric.path.read_text(encoding="utf-8"))
            except (OSError, ValueError) as exc:
                summary.skipped.append(f"{metric.path.name}: {exc}")
                continue
            # A JSON object is a single sample; a JSON array of objects is a real
            # time series (reward per episode, score per step, ...) and becomes one
            # message per element so Foxglove's Plot panel draws a curve.
            if isinstance(raw, dict):
                records = [raw]
            elif isinstance(raw, list) and all(isinstance(item, dict) for item in raw):
                records = raw
            else:
                summary.skipped.append(
                    f"{metric.path.name}: not a JSON object or array of objects"
                )
                continue
            if not records:
                summary.skipped.append(f"{metric.path.name}: empty metrics document")
                continue
            topic = safe_topic(metric.name, prefix=metrics_topic_prefix)
            for offset, record in enumerate(records):
                flat = _flatten_metric_payload(record)
                timestamp_ns = base_ns + (index if len(records) == 1 else offset) * step_ns
                if topic not in metric_channels:
                    schema_id = writer.register_schema(
                        name=f"npa.RunMetrics.{metric.name}",
                        encoding="jsonschema",
                        data=json.dumps(
                            _metric_schema(flat, f"npa.RunMetrics.{metric.name}")
                        ).encode("utf-8"),
                    )
                    metric_channels[topic] = writer.register_channel(
                        topic=topic, message_encoding="json", schema_id=schema_id
                    )
                message = dict(flat)
                message["timestamp"] = _time_fields(timestamp_ns)
                writer.add_message(
                    channel_id=metric_channels[topic],
                    log_time=timestamp_ns,
                    data=json.dumps(message).encode("utf-8"),
                    publish_time=timestamp_ns,
                    sequence=offset,
                )
                summary.metrics += 1
                summary.channels[topic] = summary.channels.get(topic, 0) + 1
                first_ns = timestamp_ns if not first_ns else min(first_ns, timestamp_ns)
                last_ns = max(last_ns, timestamp_ns)

        log_sequence = 0
        for entry in log_list:
            try:
                text = entry.path.read_text(encoding="utf-8", errors="replace")
            except OSError as exc:
                summary.skipped.append(f"{entry.path.name}: {exc}")
                continue
            lines = [line for line in text.splitlines() if line.strip()]
            if not lines:
                continue
            if log_schema_id is None:
                log_schema_id = writer.register_schema(
                    name="foxglove.Log",
                    encoding="jsonschema",
                    data=json.dumps(LOG_SCHEMA).encode("utf-8"),
                )
            if log_channel_id is None:
                log_channel_id = writer.register_channel(
                    topic="/log", message_encoding="json", schema_id=log_schema_id
                )
            level = LOG_LEVELS.get(str(entry.level).lower(), LOG_LEVELS["info"])
            for line in lines:
                timestamp_ns = base_ns + log_sequence * step_ns
                message = {
                    "timestamp": _time_fields(timestamp_ns),
                    "level": level,
                    "message": line[:8000],
                    "name": entry.name,
                    "file": entry.path.name,
                    "line": 0,
                }
                writer.add_message(
                    channel_id=log_channel_id,
                    log_time=timestamp_ns,
                    data=json.dumps(message).encode("utf-8"),
                    publish_time=timestamp_ns,
                    sequence=log_sequence,
                )
                summary.logs += 1
                summary.channels["/log"] = summary.channels.get("/log", 0) + 1
                first_ns = timestamp_ns if not first_ns else min(first_ns, timestamp_ns)
                last_ns = max(last_ns, timestamp_ns)
                log_sequence += 1

        writer.add_metadata(
            name="npa",
            data={
                "producer": "npa workbench foxglove convert-run",
                "run_id": str(run_id or ""),
                # Be explicit: these are not sensor capture times.
                "timestamps": "synthetic-fps",
                "fps": str(rate),
                "frames": str(summary.frames),
                "metrics": str(summary.metrics),
                "logs": str(summary.logs),
            },
        )
        writer.finish()

    if summary.frames + summary.metrics + summary.logs == 0:
        target.unlink(missing_ok=True)
        raise McapWriteError(
            "no artifacts could be converted (all inputs were unreadable or unsupported)"
        )

    summary.message_count = summary.frames + summary.metrics + summary.logs
    summary.size_bytes = target.stat().st_size
    summary.start_time_ns = first_ns
    summary.end_time_ns = last_ns
    return summary


def _default_start_ns(
    frames: list[FrameInput],
    metrics: list[MetricsInput],
    logs: list[LogInput],
) -> int:
    """Anchor the synthetic clock on the earliest artifact mtime (real wall time)."""
    candidates: list[float] = []
    sources: list[FrameInput | MetricsInput | LogInput] = [*frames, *metrics, *logs]
    for item in sources:
        try:
            candidates.append(item.path.stat().st_mtime)
        except OSError:
            continue
    if not candidates:
        return 0
    return int(min(candidates) * NS_PER_S)


def convert_run_directory(
    *,
    input_path: str | Path,
    output: str | Path,
    fps: float = 10.0,
    max_frames: int = 0,
    run_id: str = "",
) -> McapSummary:
    """Discover a run directory's artifacts and write them as one MCAP file."""
    frames, metrics, logs, skipped = collect_run_inputs(input_path, max_frames=max_frames)
    summary = write_run_mcap(
        output=output,
        frames=frames,
        metrics=metrics,
        logs=logs,
        fps=fps,
        run_id=run_id,
    )
    summary.skipped = [*skipped, *summary.skipped]
    return summary
