"""Render the per-cluster Terraform wrapper (main.tf) + ``terraform.tfvars``.

Each fleet cluster is one k8s-training deployment. The wrapper ``main.tf`` is a
template with two substitution points -- the k8s-training module ``source`` and
the provider ``domain`` (region dependent) -- so a fleet can consume either the
repo-vendored recipe or a freshly cloned upstream ``k8s-training`` (latest).
"""

from __future__ import annotations

from pathlib import Path

from npa.fleet.spec import ClusterSpec

_TEMPLATE_DIR = Path(__file__).resolve().parent / "terraform"
_MAIN_TEMPLATE = _TEMPLATE_DIR / "main.tf.tpl"
_VARIABLES_FILE = _TEMPLATE_DIR / "variables.tf"


def provider_domain(region: str) -> str:
    """Nebius Terraform provider domain for *region* (EU vs. global)."""

    return "api.eu.nebius.cloud:443" if region.startswith("eu") else "api.nebius.cloud:443"


def render_main_tf(*, k8s_training_source: str, region: str) -> str:
    """Return the wrapper ``main.tf`` with source + provider domain filled in."""

    text = _MAIN_TEMPLATE.read_text()
    text = text.replace("__K8S_TRAINING_SOURCE__", k8s_training_source)
    text = text.replace("__PROVIDER_DOMAIN__", provider_domain(region))
    return text


def variables_tf() -> str:
    """Return the static wrapper ``variables.tf`` content."""

    return _VARIABLES_FILE.read_text()


def _tfstr(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_tfvars(cluster: ClusterSpec) -> str:
    """Return ``terraform.tfvars`` for a single resolved cluster."""

    cpu = cluster.cpu_nodes
    gpu = cluster.gpu_nodes
    lines: list[str] = [
        "# Generated by `npa fleet`.",
        f"cluster_name = {_tfstr(cluster.name)}",
    ]
    if cluster.k8s_version:
        lines.append(f"k8s_version = {_tfstr(cluster.k8s_version)}")
    if cluster.subnet_id:
        lines.append(f"subnet_id = {_tfstr(cluster.subnet_id)}")

    cpu_count = cpu.count if cpu else 0
    lines.append(f"cpu_nodes_count = {cpu_count}")
    if cpu and cpu.count > 0:
        lines.append(f"cpu_nodes_platform = {_tfstr(cpu.platform)}")
        if cpu.preset:
            lines.append(f"cpu_nodes_preset = {_tfstr(cpu.preset)}")

    gpu_count = gpu.count if gpu else 0
    lines.append(f"gpu_nodes_count = {gpu_count}")
    if gpu and gpu.count > 0:
        lines.append(f"gpu_nodes_platform = {_tfstr(gpu.platform)}")
        if gpu.preset:
            lines.append(f"gpu_nodes_preset = {_tfstr(gpu.preset)}")
        if gpu.disk_size_gib > 0:
            lines.append(f"gpu_disk_size = {_tfstr(str(gpu.disk_size_gib))}")
        else:
            lines.append(f"gpu_disk_size = {_tfstr(str(cluster.gpu_disk_size_gib))}")

    lines.append(f"enable_gpu_cluster = {'true' if cluster.resolved_enable_gpu_cluster() else 'false'}")
    if cluster.infiniband_fabric:
        lines.append(f"infiniband_fabric = {_tfstr(cluster.infiniband_fabric)}")

    lines.append(f"enable_filestore = {'true' if cluster.enable_filestore else 'false'}")
    if cluster.existing_filestore:
        lines.append(f"existing_filestore = {_tfstr(cluster.existing_filestore)}")
    lines.append(f"filestore_disk_size_gibibytes = {cluster.filestore_disk_size_gibibytes}")

    return "\n".join(lines) + "\n"
