"""Terraform CLI wrapper for infrastructure provisioning."""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import threading
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator

# The Nebius Terraform provider prefers an ambient NEBIUS_IAM_TOKEN over the
# explicit `token = var.iam_token` in the provider block. A stale/expired token
# in the environment (a common trap: it can be carried by a long-lived tmux
# server or exported by a shell profile) therefore shadows the fresh token this
# deploy mints via `get_iam_token()`, breaking `terraform apply/destroy` with
# PermissionDenied / Unauthenticated even though the CLI works. Strip these keys
# from the Terraform subprocess env so the fresh `-var iam_token` is always used.
_IAM_TOKEN_ENV_KEYS = ("NEBIUS_IAM_TOKEN", "NPA_NEBIUS_IAM_TOKEN")


class ProvisionerError(Exception):
    pass


_BUNDLED_TF_DIR = Path(__file__).parent / "terraform"
_WORKBENCH_BASE = Path.home() / ".npa" / "workbenches"
# Shared Terraform plugin cache so every fresh per-deploy work dir reuses
# already-downloaded providers instead of re-fetching them from
# registry.terraform.io. This makes `terraform init` faster and resilient to
# transient registry outages (a warm cache needs no network at all). Overridable
# via the standard TF_PLUGIN_CACHE_DIR env var.
_TF_PLUGIN_CACHE_DIR = Path.home() / ".npa" / "terraform-plugin-cache"
# Substrings that identify a transient `terraform init` failure worth retrying
# (registry/network hiccups) rather than a real configuration error.
_TRANSIENT_INIT_MARKERS = (
    "could not connect to registry",
    "failed to request discovery document",
    "timeout exceeded while awaiting headers",
    "failed to retrieve",
    "no such host",
    "connection reset",
    "connection refused",
    "temporary failure in name resolution",
    "i/o timeout",
    "tls handshake timeout",
    "eof",
)
DEFAULT_VM_BOOT_DISK_SIZE_GB = 100
DEFAULT_CONTAINER_BOOT_DISK_SIZE_GB = 250

# Template for the S3 backend block.  Bucket, key, endpoint, and region are
# baked into the file so that ``endpoints`` (the newer Terraform >=1.6 syntax)
# works correctly — it cannot be set via ``-backend-config`` flat keys.
# Only credentials are passed at init time via ``-backend-config``.
_BACKEND_TF_TEMPLATE = """\
# Auto-generated by npa — do not edit.
terraform {{
  backend "s3" {{
    bucket = "{bucket}"
    key    = "npa/terraform-state/{project}/{name}/terraform.tfstate"

    endpoints = {{
      s3 = "{endpoint}"
    }}
    region = "{region}"

    skip_region_validation      = true
    skip_credentials_validation = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
    use_path_style              = true
  }}
}}
"""


def _require_terraform() -> str:
    tf = shutil.which("terraform")
    if tf is None:
        raise ProvisionerError(
            "terraform binary not found on PATH. "
            "Install it: https://developer.hashicorp.com/terraform/install"
        )
    return tf


def _tf_env() -> dict[str, str]:
    """Return the subprocess env for terraform with a warm plugin cache.

    Also strips stale Nebius IAM tokens (_IAM_TOKEN_ENV_KEYS) so a fresh
    ``-var iam_token`` is always used instead of an ambient token that the
    provider would otherwise prefer (causing PermissionDenied / Unauthenticated).
    """
    env = dict(os.environ)
    for key in _IAM_TOKEN_ENV_KEYS:
        env.pop(key, None)
    if not env.get("TF_PLUGIN_CACHE_DIR"):
        cache = _TF_PLUGIN_CACHE_DIR
        try:
            cache.mkdir(parents=True, exist_ok=True)
        except OSError:
            return env
        env["TF_PLUGIN_CACHE_DIR"] = str(cache)
    return env


def _run(
    args: list[str],
    *,
    cwd: str | Path,
    capture: bool = False,
    stream: bool = False,
) -> subprocess.CompletedProcess[str]:
    tf = _require_terraform()
    cmd = [tf] + args
    kwargs: dict[str, Any] = {"cwd": str(cwd), "text": True, "env": _tf_env()}

    if stream and args and args[0] == "destroy":
        return _run_destroy_stream(cmd, cwd=Path(cwd), env=kwargs["env"])

    if capture:
        kwargs["capture_output"] = True
    elif stream:
        kwargs["stdout"] = sys.stdout
        kwargs["stderr"] = subprocess.PIPE
    else:
        kwargs["capture_output"] = True

    result = subprocess.run(cmd, **kwargs)
    if stream and result.stderr:
        sys.stderr.write(result.stderr)
        sys.stderr.flush()
    if result.returncode != 0 and capture:
        stderr = result.stderr or ""
        raise ProvisionerError(
            f"terraform {args[0]} failed (exit {result.returncode}):\n{stderr.strip()}"
        )
    return result


_ANSI_ESCAPE_RE = re.compile(r"\x1b\[[0-?]*[ -/]*[@-~]")
_DEPRECATED_GPU_OUTPUT_RE = re.compile(
    r"^\s*[+~-]\s+gpu_(?:platform|preset)\s+="
)


def _filter_destroy_output_line(line: str) -> str:
    """Hide deprecated Terraform output aliases from human destroy progress.

    The aliases remain in the machine-readable Terraform schema for compatible
    GPU callers, but a CPU agent's destroy plan must not label ``cpu-d3`` or
    ``8vcpu-32gb`` as GPU facts. Canonical ``platform``/``preset`` and
    ``cpu_platform``/``cpu_preset`` lines remain visible.
    """

    plain = _ANSI_ESCAPE_RE.sub("", line)
    return "" if _DEPRECATED_GPU_OUTPUT_RE.match(plain) else line


def _run_destroy_stream(
    cmd: list[str], *, cwd: Path, env: dict[str, str]
) -> subprocess.CompletedProcess[str]:
    """Stream Terraform destroy while filtering only deprecated output aliases."""

    process = subprocess.Popen(
        cmd,
        cwd=str(cwd),
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        bufsize=1,
    )
    stdout_lines: list[str] = []
    stderr_lines: list[str] = []

    def _pump_stdout() -> None:
        assert process.stdout is not None
        for line in process.stdout:
            stdout_lines.append(line)
            visible = _filter_destroy_output_line(line)
            if visible:
                sys.stdout.write(visible)
                sys.stdout.flush()

    def _pump_stderr() -> None:
        assert process.stderr is not None
        for line in process.stderr:
            stderr_lines.append(line)
            sys.stderr.write(line)
            sys.stderr.flush()

    threads = [
        threading.Thread(target=_pump_stdout, name="npa-terraform-stdout", daemon=True),
        threading.Thread(target=_pump_stderr, name="npa-terraform-stderr", daemon=True),
    ]
    for thread in threads:
        thread.start()
    returncode = process.wait()
    for thread in threads:
        thread.join()
    return subprocess.CompletedProcess(
        args=cmd,
        returncode=returncode,
        stdout="".join(stdout_lines),
        stderr="".join(stderr_lines),
    )


def _build_var_args(tf_vars: dict[str, str]) -> list[str]:
    args: list[str] = []
    for key, value in tf_vars.items():
        args.extend(["-var", f"{key}={value}"])
    return args


#: Variable names whose values must not reach the process table. `ps` is readable
#: by every local user, so `-var iam_token=...` / `-var nebius_secret_key=...`
#: leaked the deploy's IAM token and the state bucket's S3 keys for the duration
#: of the apply. Those values go through a 0600 var-file instead.
_SENSITIVE_VAR_HINTS = ("token", "secret", "password", "api_key", "_key")
_SENSITIVE_VAR_FILE = "npa-sensitive.tfvars.json"


def _is_sensitive_var(name: str) -> bool:
    lowered = str(name or "").lower()
    if lowered.endswith("_key_path") or lowered.endswith("_path"):
        return False
    return any(hint in lowered for hint in _SENSITIVE_VAR_HINTS)


def _split_sensitive_vars(tf_vars: dict[str, str]) -> tuple[dict[str, str], dict[str, str]]:
    sensitive = {
        key: value
        for key, value in tf_vars.items()
        if _is_sensitive_var(key) and str(value or "") != ""
    }
    plain = {key: value for key, value in tf_vars.items() if key not in sensitive}
    return sensitive, plain


@contextmanager
def _var_args(tf_dir: Path, tf_vars: dict[str, str]) -> Iterator[list[str]]:
    """Yield terraform var arguments, keeping secret values out of argv.

    The file is written 0600 inside the per-deploy working directory (itself
    0700) and removed when the command finishes. It is deliberately *not* named
    ``*.auto.tfvars.json``, so it only applies to the command that passes it.
    """
    sensitive, plain = _split_sensitive_vars(tf_vars)
    if not sensitive:
        yield _build_var_args(plain)
        return
    path = Path(tf_dir) / _SENSITIVE_VAR_FILE
    path.write_text(json.dumps(sensitive, sort_keys=True), encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:  # pragma: no cover - unusual filesystems
        pass
    try:
        yield [f"-var-file={path}", *_build_var_args(plain)]
    finally:
        path.unlink(missing_ok=True)


def _runtime_value(runtime: Any) -> str:
    return str(getattr(runtime, "value", runtime))


def resolve_boot_disk_size_gb(runtime: Any, disk_size: int | None = None) -> int | None:
    """Return the boot disk size override for Terraform.

    VM deploys intentionally return ``None`` by default so the Terraform
    module keeps its existing default. Container deploys need a larger boot
    disk because image pulls and unpacked layers are written to the root disk.
    """
    if disk_size is not None:
        if disk_size <= 0:
            raise ValueError(f"--disk-size must be positive, got {disk_size}")
        return disk_size
    if _runtime_value(runtime) == "container":
        return DEFAULT_CONTAINER_BOOT_DISK_SIZE_GB
    return None


def boot_disk_tf_vars(runtime: Any, disk_size: int | None = None) -> dict[str, str]:
    size = resolve_boot_disk_size_gb(runtime, disk_size)
    if size is None:
        return {}
    return {"boot_disk_size_gb": str(size)}


def apply_boot_disk_tf_vars(
    tf_vars: dict[str, str],
    runtime: Any,
    disk_size: int | None = None,
) -> None:
    disk_vars = boot_disk_tf_vars(runtime, disk_size)
    if disk_vars and (disk_size is not None or "boot_disk_size_gb" not in tf_vars):
        tf_vars.update(disk_vars)


# Platforms that reject older public CUDA12 images (need nvidia drivers 580.x).
DEFAULT_CUDA13_IMAGE_FAMILY = "ubuntu24.04-cuda13.0"
_PLATFORMS_REQUIRING_CUDA13_IMAGE = frozenset(
    {
        "gpu-rtx6000",
        "gpu-b300-sxm",
    }
)


def default_image_family_for_platform(gpu_platform: str) -> str | None:
    """Return a boot image family override for GPU platforms that need it."""
    platform = (gpu_platform or "").strip().lower()
    if platform in _PLATFORMS_REQUIRING_CUDA13_IMAGE:
        return DEFAULT_CUDA13_IMAGE_FAMILY
    return None


def apply_default_image_family(tf_vars: dict[str, str], gpu_platform: str) -> None:
    """Set ``image_family`` when unset and the GPU platform requires CUDA 13 / driver 580."""
    if "image_family" in tf_vars:
        return
    family = default_image_family_for_platform(gpu_platform)
    if family:
        tf_vars["image_family"] = family


# ── Working directory management ─────────────────────────────────────────


def prepare_working_dir(
    project: str,
    name: str,
    *,
    bucket: str,
    region: str,
    endpoint: str,
) -> Path:
    """Create or update a per-instance Terraform working directory.

    Copies the bundled .tf and .tpl files into
    ``~/.npa/workbenches/{project}/{name}/`` and writes a ``backend.tf``
    for S3 remote state.  Returns the working directory path.
    """
    work_dir = _WORKBENCH_BASE / project / name
    work_dir.mkdir(parents=True, exist_ok=True)

    # Copy every file from the bundled Terraform directory.
    for src in _BUNDLED_TF_DIR.iterdir():
        if src.is_file():
            shutil.copy2(src, work_dir / src.name)

    # Write the S3 backend block with environment-specific values.
    backend_tf = _BACKEND_TF_TEMPLATE.format(
        bucket=bucket,
        project=project,
        name=name,
        endpoint=endpoint,
        region=region,
    )
    (work_dir / "backend.tf").write_text(backend_tf)

    return work_dir


def working_dir_path(project: str, name: str) -> Path:
    """Return the path to a workbench's Terraform working directory."""
    return _WORKBENCH_BASE / project / name


def cleanup_working_dir(project: str, name: str) -> None:
    """Remove the per-instance working directory."""
    work_dir = _WORKBENCH_BASE / project / name
    if work_dir.exists():
        shutil.rmtree(work_dir)


# ── Terraform commands ───────────────────────────────────────────────────


def _looks_transient_init_failure(message: str) -> bool:
    lowered = (message or "").lower()
    return any(marker in lowered for marker in _TRANSIENT_INIT_MARKERS)


def init(
    tf_dir: str | Path | None = None,
    backend_config: dict[str, str] | None = None,
    *,
    retries: int = 3,
    backoff_seconds: float = 4.0,
    sleep: Any = time.sleep,
) -> None:
    """Run terraform init.

    If *backend_config* is provided, each key/value pair is passed as a
    ``-backend-config`` flag.  Typically only ``access_key`` and
    ``secret_key`` are passed here — the rest is embedded in ``backend.tf``.

    Provider installation from registry.terraform.io can fail transiently
    (timeouts, DNS blips); those are retried with exponential backoff so a fresh
    VM is not rolled back over a momentary registry hiccup. Non-transient
    failures (e.g. a real config error) raise immediately.
    """
    tf_dir = Path(tf_dir) if tf_dir else _BUNDLED_TF_DIR
    args = ["init", "-input=false"]
    if backend_config:
        args.append("-reconfigure")
        for key, value in backend_config.items():
            args.extend(["-backend-config", f"{key}={value}"])
    delay = backoff_seconds
    for attempt in range(1, max(1, retries) + 1):
        try:
            _run(args, cwd=tf_dir, capture=True)
            return
        except ProvisionerError as exc:
            if attempt >= retries or not _looks_transient_init_failure(str(exc)):
                raise
            sys.stderr.write(
                f"  terraform init attempt {attempt}/{retries} hit a transient "
                f"registry/network error; retrying in {delay:.0f}s...\n"
            )
            sys.stderr.flush()
            sleep(delay)
            delay *= 2


def plan(
    tf_dir: str | Path | None = None,
    tf_vars: dict[str, str] | None = None,
) -> str:
    """Run terraform plan, return human-readable summary."""
    tf_dir = Path(tf_dir) if tf_dir else _BUNDLED_TF_DIR
    with _var_args(tf_dir, tf_vars or {}) as var_args:
        result = _run(["plan", "-input=false", "-no-color", *var_args], cwd=tf_dir, capture=True)
    return result.stdout


def apply(
    tf_dir: str | Path | None = None,
    tf_vars: dict[str, str] | None = None,
    *,
    stream: bool = True,
) -> dict[str, Any]:
    """Run terraform apply -auto-approve, return outputs dict."""
    tf_dir = Path(tf_dir) if tf_dir else _BUNDLED_TF_DIR
    with _var_args(tf_dir, tf_vars or {}) as var_args:
        result = _run(
            ["apply", "-auto-approve", "-input=false", *var_args], cwd=tf_dir, stream=stream
        )
    if result.returncode != 0:
        stderr = (result.stderr or "").strip()
        detail = f":\n{stderr}" if stderr else ""
        raise ProvisionerError(f"terraform apply failed (exit {result.returncode}){detail}")
    return outputs(tf_dir)


def destroy(
    tf_dir: str | Path | None = None,
    tf_vars: dict[str, str] | None = None,
    *,
    stream: bool = True,
    targets: list[str] | None = None,
) -> None:
    """Run terraform destroy -auto-approve."""
    tf_dir = Path(tf_dir) if tf_dir else _BUNDLED_TF_DIR
    args = ["destroy", "-auto-approve", "-input=false"]
    if targets:
        for target in targets:
            args.extend(["-target", target])
    with _var_args(tf_dir, tf_vars or {}) as var_args:
        result = _run([*args, *var_args], cwd=tf_dir, stream=stream)
    if result.returncode != 0:
        stderr = (result.stderr or "").strip()
        detail = f":\n{stderr}" if stderr else ""
        raise ProvisionerError(f"terraform destroy failed (exit {result.returncode}){detail}")


def state_list(tf_dir: str | Path | None = None) -> list[str]:
    """Run terraform state list and return managed resource addresses."""
    tf_dir = Path(tf_dir) if tf_dir else _BUNDLED_TF_DIR
    result = _run(["state", "list"], cwd=tf_dir, capture=True)
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def outputs(tf_dir: str | Path | None = None) -> dict[str, Any]:
    """Run terraform output -json, parse and return dict of {key: value}."""
    tf_dir = Path(tf_dir) if tf_dir else _BUNDLED_TF_DIR
    result = _run(["output", "-json"], cwd=tf_dir, capture=True)
    raw = json.loads(result.stdout)
    # Terraform output -json returns {"key": {"value": ..., "type": ...}}
    return {key: entry["value"] for key, entry in raw.items()}
