"""Terraform CLI wrapper for infrastructure provisioning."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from io import StringIO
from pathlib import Path
from typing import Any, TextIO


class ProvisionerError(Exception):
    pass


_BUNDLED_TF_DIR = Path(__file__).parent / "terraform"
_WORKBENCH_BASE = Path.home() / ".npa" / "workbenches"
DEFAULT_VM_BOOT_DISK_SIZE_GB = 100
DEFAULT_CONTAINER_BOOT_DISK_SIZE_GB = 250

# Template for the S3 backend block.  Bucket, key, endpoint, and region are
# baked into the file so that ``endpoints`` (the newer Terraform >=1.6 syntax)
# works correctly — it cannot be set via ``-backend-config`` flat keys.
# Only credentials are passed at init time via ``-backend-config``.
_BACKEND_TF_TEMPLATE = """\
# Auto-generated by npa — do not edit.
terraform {{
  backend "s3" {{
    bucket = "{bucket}"
    key    = "npa/terraform-state/{project}/{name}/terraform.tfstate"

    endpoints = {{
      s3 = "{endpoint}"
    }}
    region = "{region}"

    skip_region_validation      = true
    skip_credentials_validation = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
    use_path_style              = true
  }}
}}
"""


def _require_terraform() -> str:
    tf = shutil.which("terraform")
    if tf is None:
        raise ProvisionerError(
            "terraform binary not found on PATH. "
            "Install it: https://developer.hashicorp.com/terraform/install"
        )
    return tf


class _TeeStream(TextIO):
    """Write to a buffer and an underlying stream (for streamed terraform stderr)."""

    def __init__(self, buffer: StringIO, underlying: TextIO) -> None:
        self._buffer = buffer
        self._underlying = underlying

    def write(self, data: str) -> int:
        self._buffer.write(data)
        return self._underlying.write(data)

    def flush(self) -> None:
        self._buffer.flush()
        self._underlying.flush()


def _run(
    args: list[str],
    *,
    cwd: str | Path,
    capture: bool = False,
    stream: bool = False,
) -> subprocess.CompletedProcess[str]:
    tf = _require_terraform()
    cmd = [tf] + args
    kwargs: dict[str, Any] = {"cwd": str(cwd), "text": True}

    stderr_buffer: StringIO | None = None
    if capture:
        kwargs["capture_output"] = True
    elif stream:
        stderr_buffer = StringIO()
        kwargs["stdout"] = sys.stdout
        kwargs["stderr"] = _TeeStream(stderr_buffer, sys.stderr)
    else:
        kwargs["capture_output"] = True

    result = subprocess.run(cmd, **kwargs)
    if stderr_buffer is not None:
        result.stderr = stderr_buffer.getvalue()
    if result.returncode != 0 and capture:
        stderr = result.stderr or ""
        raise ProvisionerError(
            f"terraform {args[0]} failed (exit {result.returncode}):\n{stderr.strip()}"
        )
    return result


def _build_var_args(tf_vars: dict[str, str]) -> list[str]:
    args: list[str] = []
    for key, value in tf_vars.items():
        args.extend(["-var", f"{key}={value}"])
    return args


def _runtime_value(runtime: Any) -> str:
    return str(getattr(runtime, "value", runtime))


def resolve_boot_disk_size_gb(runtime: Any, disk_size: int | None = None) -> int | None:
    """Return the boot disk size override for Terraform.

    VM deploys intentionally return ``None`` by default so the Terraform
    module keeps its existing default. Container deploys need a larger boot
    disk because image pulls and unpacked layers are written to the root disk.
    """
    if disk_size is not None:
        if disk_size <= 0:
            raise ValueError(f"--disk-size must be positive, got {disk_size}")
        return disk_size
    if _runtime_value(runtime) == "container":
        return DEFAULT_CONTAINER_BOOT_DISK_SIZE_GB
    return None


def boot_disk_tf_vars(runtime: Any, disk_size: int | None = None) -> dict[str, str]:
    size = resolve_boot_disk_size_gb(runtime, disk_size)
    if size is None:
        return {}
    return {"boot_disk_size_gb": str(size)}


def apply_boot_disk_tf_vars(
    tf_vars: dict[str, str],
    runtime: Any,
    disk_size: int | None = None,
) -> None:
    disk_vars = boot_disk_tf_vars(runtime, disk_size)
    if disk_vars and (disk_size is not None or "boot_disk_size_gb" not in tf_vars):
        tf_vars.update(disk_vars)


# ── Working directory management ─────────────────────────────────────────


def prepare_working_dir(
    project: str,
    name: str,
    *,
    bucket: str,
    region: str,
    endpoint: str,
) -> Path:
    """Create or update a per-instance Terraform working directory.

    Copies the bundled .tf and .tpl files into
    ``~/.npa/workbenches/{project}/{name}/`` and writes a ``backend.tf``
    for S3 remote state.  Returns the working directory path.
    """
    work_dir = _WORKBENCH_BASE / project / name
    work_dir.mkdir(parents=True, exist_ok=True)

    # Copy every file from the bundled Terraform directory.
    for src in _BUNDLED_TF_DIR.iterdir():
        if src.is_file():
            shutil.copy2(src, work_dir / src.name)

    # Write the S3 backend block with environment-specific values.
    backend_tf = _BACKEND_TF_TEMPLATE.format(
        bucket=bucket,
        project=project,
        name=name,
        endpoint=endpoint,
        region=region,
    )
    (work_dir / "backend.tf").write_text(backend_tf)

    return work_dir


def working_dir_path(project: str, name: str) -> Path:
    """Return the path to a workbench's Terraform working directory."""
    return _WORKBENCH_BASE / project / name


def cleanup_working_dir(project: str, name: str) -> None:
    """Remove the per-instance working directory."""
    work_dir = _WORKBENCH_BASE / project / name
    if work_dir.exists():
        shutil.rmtree(work_dir)


# ── Terraform commands ───────────────────────────────────────────────────


def init(
    tf_dir: str | Path | None = None,
    backend_config: dict[str, str] | None = None,
) -> None:
    """Run terraform init.

    If *backend_config* is provided, each key/value pair is passed as a
    ``-backend-config`` flag.  Typically only ``access_key`` and
    ``secret_key`` are passed here — the rest is embedded in ``backend.tf``.
    """
    tf_dir = Path(tf_dir) if tf_dir else _BUNDLED_TF_DIR
    args = ["init", "-input=false"]
    if backend_config:
        args.append("-reconfigure")
        for key, value in backend_config.items():
            args.extend(["-backend-config", f"{key}={value}"])
    _run(args, cwd=tf_dir, capture=True)


def plan(
    tf_dir: str | Path | None = None,
    tf_vars: dict[str, str] | None = None,
) -> str:
    """Run terraform plan, return human-readable summary."""
    tf_dir = Path(tf_dir) if tf_dir else _BUNDLED_TF_DIR
    args = ["plan", "-input=false", "-no-color"]
    args.extend(_build_var_args(tf_vars or {}))
    result = _run(args, cwd=tf_dir, capture=True)
    return result.stdout


def apply(
    tf_dir: str | Path | None = None,
    tf_vars: dict[str, str] | None = None,
    *,
    stream: bool = True,
) -> dict[str, Any]:
    """Run terraform apply -auto-approve, return outputs dict."""
    tf_dir = Path(tf_dir) if tf_dir else _BUNDLED_TF_DIR
    args = ["apply", "-auto-approve", "-input=false"]
    args.extend(_build_var_args(tf_vars or {}))
    result = _run(args, cwd=tf_dir, stream=stream)
    if result.returncode != 0:
        stderr = (result.stderr or "").strip()
        detail = f":\n{stderr}" if stderr else ""
        raise ProvisionerError(f"terraform apply failed (exit {result.returncode}){detail}")
    return outputs(tf_dir)


def destroy(
    tf_dir: str | Path | None = None,
    tf_vars: dict[str, str] | None = None,
    *,
    stream: bool = True,
) -> None:
    """Run terraform destroy -auto-approve."""
    tf_dir = Path(tf_dir) if tf_dir else _BUNDLED_TF_DIR
    args = ["destroy", "-auto-approve", "-input=false"]
    args.extend(_build_var_args(tf_vars or {}))
    result = _run(args, cwd=tf_dir, stream=stream)
    if result.returncode != 0:
        raise ProvisionerError(f"terraform destroy failed (exit {result.returncode})")


def state_list(tf_dir: str | Path | None = None) -> list[str]:
    """Run terraform state list and return managed resource addresses."""
    tf_dir = Path(tf_dir) if tf_dir else _BUNDLED_TF_DIR
    result = _run(["state", "list"], cwd=tf_dir, capture=True)
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def outputs(tf_dir: str | Path | None = None) -> dict[str, Any]:
    """Run terraform output -json, parse and return dict of {key: value}."""
    tf_dir = Path(tf_dir) if tf_dir else _BUNDLED_TF_DIR
    result = _run(["output", "-json"], cwd=tf_dir, capture=True)
    raw = json.loads(result.stdout)
    # Terraform output -json returns {"key": {"value": ..., "type": ...}}
    return {key: entry["value"] for key, entry in raw.items()}
