"""Delete exact versions of objects created under a live test's owned prefix."""

from typing import Any


def list_owned_versions(s3: Any, bucket: str, prefix: str) -> list[dict[str, str]]:
    """Inventory object versions and delete markers under a test-owned prefix.

    Args:
        s3: Client for the explicitly selected test project.
        bucket: Bucket containing the fixture.
        prefix: Unique prefix generated by this test, ending with a slash.

    Returns:
        Exact key/version identities, including delete markers.

    Raises:
        ValueError: The prefix is invalid or a listing crosses its boundary.
    """
    if not prefix or not prefix.strip("/") or not prefix.endswith("/"):
        raise ValueError("cleanup requires a nonempty, slash-terminated owned prefix")
    versions: list[dict[str, str]] = []
    paginator = s3.get_paginator("list_object_versions")
    for page in paginator.paginate(Bucket=bucket, Prefix=prefix):
        for item in [*page.get("Versions", []), *page.get("DeleteMarkers", [])]:
            if not str(item["Key"]).startswith(prefix):
                raise ValueError("S3 listing returned a key outside the owned prefix")
            versions.append({"Key": item["Key"], "VersionId": item["VersionId"]})
    return versions


def delete_owned_prefix(s3: Any, bucket: str, prefix: str) -> None:
    """Delete a fixture's exact versions and verify both S3 inventories are empty.

    Args:
        s3: Client authorized to list and delete versions in the test bucket.
        bucket: Bucket containing the fixture.
        prefix: Unique slash-terminated prefix created by this test.

    Raises:
        ValueError: The prefix is empty or lacks its directory delimiter.
        RuntimeError: A deletion failed or fixture data remains.
    """
    versions = list_owned_versions(s3, bucket, prefix)
    errors: list[dict[str, Any]] = []
    for start in range(0, len(versions), 1000):
        response = s3.delete_objects(
            Bucket=bucket, Delete={"Objects": versions[start : start + 1000]}
        )
        errors.extend(response.get("Errors") or [])
    if errors:
        raise RuntimeError(
            f"failed to delete {len(errors)} fixture version(s): {errors}"
        )
    remaining = s3.list_objects_v2(Bucket=bucket, Prefix=prefix, MaxKeys=1)
    if remaining.get("Contents"):
        raise RuntimeError("fixture objects remain after cleanup")
    if list_owned_versions(s3, bucket, prefix):
        raise RuntimeError(
            "fixture object versions or delete markers remain after cleanup"
        )
