ARG NPA_ISAAC_LAB_BASE_DIGEST=sha256:bb735577809f9b427493fda78efebc543dcf02e3deac2ec8a36ac019bff8ee46

FROM ghcr.io/nebius/nebius-physical-ai/npa-isaac-lab@${NPA_ISAAC_LAB_BASE_DIGEST}

ARG BYOF_RUN_ID=placeholder

LABEL byof.test="true" \
      byof.test.run_id="${BYOF_RUN_ID}"

COPY custom_train.py /opt/byof/custom_train.py

USER 1000
