ARG NPA_ISAAC_LAB_BASE_IMAGE

FROM ${NPA_ISAAC_LAB_BASE_IMAGE}

ARG BYOF_RUN_ID=placeholder

LABEL byof.test="true" \
      byof.test.run_id="${BYOF_RUN_ID}"

COPY custom_train.py /opt/byof/custom_train.py

USER 1000
