"""Verify interrupted reports recover without overwrites or final-cohort access."""

import json
from types import SimpleNamespace

import pytest

from npa.clients.storage import StoragePreconditionFailed
from npa.workflows.field_failure import reference_demo_publication as publication


class ConditionalStorage:
    def __init__(self):
        self.objects = {}
        self.writes = []
        self.interrupt = None

    def put_bytes_conditional(self, data, uri, **kwargs):
        assert kwargs["if_none_match"] is True
        self.writes.append(uri)
        if uri in self.objects:
            raise StoragePreconditionFailed("fixture object already exists")
        event = self.interrupt
        if event and uri.endswith(event[0]):
            self.interrupt = None
            if event[1] == "after":
                self.objects[uri] = data
            raise OSError("fixture interrupted publication")
        self.objects[uri] = data

    def read_bytes_with_etag(self, uri):
        return (self.objects[uri], "fixture-etag") if uri in self.objects else None


@pytest.fixture
def storage(monkeypatch):
    result = ConditionalStorage()
    monkeypatch.setattr(publication, "_storage", lambda: result)
    return result


@pytest.mark.parametrize("kind", ["record", "html"])
def test_identical_retry_retains_bytes_and_conflict_is_not_overwritten(storage, kind):
    uri = "s3://example-bucket/run/report"
    publish = (
        publication.publish_record if kind == "record" else publication.publish_html
    )
    value = {"quality_passed": False} if kind == "record" else "<p>Blocked</p>"
    changed = {"quality_passed": True} if kind == "record" else "<p>Passed</p>"
    publish(uri, value)
    original = storage.objects[uri]
    publish(uri, value)
    with pytest.raises(ValueError, match="differs from regenerated bytes"):
        publish(uri, changed)
    assert storage.objects[uri] == original


def test_retry_requires_exact_bytes_not_equivalent_json(storage):
    uri = "s3://example-bucket/run/result.json"
    storage.objects[uri] = b'{"quality_passed": false}'
    with pytest.raises(ValueError, match="differs from regenerated bytes"):
        publication.publish_record(uri, {"quality_passed": False})
    assert storage.objects[uri] == b'{"quality_passed": false}'


@pytest.mark.parametrize("outcome", ["missing", "denied"])
def test_unreadable_existing_record_never_counts_as_published(
    storage, monkeypatch, outcome
):
    uri = "s3://example-bucket/run/result.json"
    storage.objects[uri] = b"existing"

    def read(_uri):
        if outcome == "denied":
            raise PermissionError("fixture read denied")
        return None

    monkeypatch.setattr(storage, "read_bytes_with_etag", read)
    with pytest.raises(PermissionError if outcome == "denied" else ValueError):
        publication.publish_record(uri, {"quality_passed": False})
    assert storage.objects[uri] == b"existing"


def _selection_records():
    from npa.workflows.field_failure.reference_demo_inputs import reference_metrics

    regions = {
        name: {"count": 1, "seeds": [i], "case_ids": [str(i)]}
        for i, name in enumerate(("office", "warehouse"))
    }
    plan = {
        "cohorts": {"regions": {"development": regions}},
        "metrics": reference_metrics(300),
    }
    records = {"reference-plan.json": plan}
    for arm, digest in (("baseline", "a"), ("candidate", "b")):
        records[f"development-{arm}.json"] = _development_record(digest)
    return records


def _development_record(digest):
    return {
        "evaluation_inputs_sha256": "c" * 64,
        "checkpoint_sha256": digest * 64,
        "success_rate": 0.0,
        "episodes": [
            {
                "case_id": str(i),
                "seed": i,
                "success": False,
                "collision_steps": 0,
                "physical_failure_steps": 0,
                "goal_distance_m": 2.0,
            }
            for i in range(2)
        ],
    }


@pytest.fixture
def selection_flow(monkeypatch, storage):
    from npa.workflows.field_failure import reference_demo_evaluate as evaluate
    from npa.workflows.field_failure import reference_demo_report as report
    from npa.workflows.field_failure import reference_demo_media as media
    from npa.workflows.field_failure import reference_demo_attribution as attribution

    args = SimpleNamespace(output_root="s3://example-bucket/run", run_id="run")
    records = _selection_records()

    def read(uri):
        name = uri.rsplit("/", 1)[-1]
        assert name in records, "must not read final artifacts"
        return records[name], "d" * 64

    for module in (evaluate, report):
        monkeypatch.setattr(module, "_read", read)
    monkeypatch.setattr(attribution, "sample_credit", lambda *_: None)
    monkeypatch.setattr(media, "preview_groups", lambda *_: [])
    monkeypatch.setattr(
        report,
        "result_summary",
        lambda _plan, selection, *_: {"quality_passed": False, "selection": selection},
    )
    monkeypatch.setattr(
        report,
        "render_html",
        lambda result, _groups: (
            "<html>" + json.dumps(result, sort_keys=True) + "</html>"
        ),
    )
    return args, records


@pytest.mark.parametrize(
    "suffix,when",
    [("result.json", "after"), ("index.html", "before"), ("index.html", "after")],
)
def test_report_retry_completes_interrupted_publication(
    selection_flow, storage, suffix, when
):
    from npa.workflows.field_failure.reference_demo_report import publish_report

    args, _records = selection_flow
    storage.interrupt = (suffix, when)
    selection = {"eligible": False}
    with pytest.raises(OSError, match="interrupted publication"):
        publish_report(args, selection=selection)
    before = dict(storage.objects)
    result = publish_report(args, selection=selection)
    assert result["quality_passed"] is False
    assert storage.objects[args.output_root + "/reports/index.html"].startswith(
        b"<html>"
    )
    assert all(storage.objects[uri] == data for uri, data in before.items())


@pytest.mark.parametrize("suffix", ["selection.json", "result.json", "index.html"])
def test_blocked_selection_retry_publishes_report_and_still_refuses_final(
    selection_flow, storage, suffix
):
    from npa.workflows.field_failure.reference_demo_evaluate import select_candidate

    args, _records = selection_flow
    storage.interrupt = (suffix, "after")
    with pytest.raises(OSError, match="interrupted publication"):
        select_candidate(args)
    before = dict(storage.objects)
    with pytest.raises(RuntimeError, match="final cohort remains untouched"):
        select_candidate(args)
    selected = json.loads(storage.objects[args.output_root + "/selection.json"])
    assert selected["eligible"] is selected["final_cohort_consumed"] is False
    assert args.output_root + "/reports/index.html" in storage.objects
    assert all(storage.objects[uri] == data for uri, data in before.items())


def test_changed_development_cannot_replace_retained_selection(selection_flow, storage):
    from npa.workflows.field_failure.reference_demo_evaluate import select_candidate

    args, records = selection_flow
    with pytest.raises(RuntimeError, match="final cohort remains untouched"):
        select_candidate(args)
    retained = dict(storage.objects)
    candidate = records["development-candidate.json"]
    candidate["episodes"][0]["success"] = True
    candidate["success_rate"] = 0.5
    with pytest.raises(ValueError, match="differs from regenerated bytes"):
        select_candidate(args)
    assert storage.objects == retained
