"""Run a deterministic native Ray Tune search and export reviewable results."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
from pathlib import Path
import re
import sys
from tempfile import TemporaryDirectory
from typing import Any, Iterable
from urllib.parse import urlsplit


SEARCH_VALUES = (0.1, 0.2, 0.3)
ARTIFACT_NAMES = ("result.json", "runtime.json", "trials.json")


def validate_settings(settings: dict[str, Any]) -> None:
    """Validate the finite synthetic search before initializing Ray.

    Args:
        settings: Iteration count, target, and optional failure value.
    Returns:
        None.
    Raises:
        ValueError: A setting cannot produce the guarded reference workload.
    """
    if not isinstance(settings.get("iterations"), int) or settings["iterations"] < 2:
        raise ValueError("iterations must be an integer of at least two")
    target = settings.get("target")
    if not isinstance(target, (int, float)) or not math.isfinite(target):
        raise ValueError("target must be finite")
    failure = settings.get("fail_value")
    if failure is not None and failure not in SEARCH_VALUES:
        raise ValueError("fail-step-size must be one of the searched values")


def validate_run_name(run_name: str) -> None:
    """Reject names that are ambiguous or can escape the storage prefix.

    Args:
        run_name: Tune experiment basename supplied by the operator.
    Returns:
        None.
    Raises:
        ValueError: The name is not a safe bounded basename.
    """
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,63}", run_name):
        raise ValueError("run-name must be a safe basename of at most 64 characters")


def _read_checkpoint() -> dict[str, Any]:
    """Read the latest trusted checkpoint supplied by Tune.

    Args:
        None.
    Returns:
        Restored iteration and injected-failure state, or initial state.
    Raises:
        ValueError: Checkpoint state has an invalid shape.
        OSError: Checkpoint bytes cannot be read.
    """
    from ray import tune

    checkpoint = tune.get_checkpoint()
    if checkpoint is None:
        return {"next_iteration": 1, "failure_injected": False}
    with checkpoint.as_directory() as directory:
        state = json.loads((Path(directory) / "state.json").read_text())
    if set(state) != {"next_iteration", "failure_injected"}:
        raise ValueError("checkpoint state has an unexpected shape")
    return state


def _report_iteration(metrics: dict[str, Any], state: dict[str, Any]) -> None:
    """Report one metric and its matching native Tune checkpoint.

    Args:
        metrics: Machine-checkable metrics for this trial iteration.
        state: State from which a retry continues.
    Returns:
        None.
    Raises:
        OSError: Temporary checkpoint bytes cannot be written.
    """
    from ray import tune

    with TemporaryDirectory() as directory:
        checkpoint_path = Path(directory) / "state.json"
        checkpoint_path.write_text(json.dumps(state, sort_keys=True) + "\n")
        checkpoint = tune.Checkpoint.from_directory(directory)
        tune.report(metrics, checkpoint=checkpoint)


def objective(config: dict[str, Any]) -> None:
    """Evaluate one deterministic step size with checkpointed iterations.

    Args:
        config: Tune trial configuration generated by the driver.
    Returns:
        None.
    Raises:
        RuntimeError: The requested one-time recovery probe is injected.
        ValueError: Restored checkpoint state is malformed.
        OSError: Checkpoint state cannot be read or written.
    """
    state = _read_checkpoint()
    resumed = state["next_iteration"] > 1
    for iteration in range(state["next_iteration"], config["iterations"] + 1):
        inject = (
            config["fail_value"] == config["step_size"]
            and not state["failure_injected"]
            and iteration == 1
        )
        state = {
            "next_iteration": iteration + 1,
            "failure_injected": inject or state["failure_injected"],
        }
        loss = (config["step_size"] - config["target"]) ** 2
        loss += (config["iterations"] - iteration) * 0.01
        _report_iteration({"loss": loss, "iteration": iteration, "resumed": resumed}, state)
        if inject:
            raise RuntimeError("intentional one-time trial failure after checkpoint")


def summarize(results: Iterable[Any], experiment_path: str) -> dict[str, Any]:
    """Validate completed trials and select the known synthetic optimum.

    Args:
        results: Result objects returned by native Tune.
        experiment_path: Tune experiment location for recovery.
    Returns:
        Validated summary and normalized per-trial records.
    Raises:
        RuntimeError: A trial failed or the expected search result is absent.
    """
    trials = []
    for result in results:
        if result.error is not None:
            raise RuntimeError(f"trial failed: {type(result.error).__name__}")
        trials.append(_trial_record(result))
    trials.sort(key=lambda trial: trial["step_size"])
    if [trial["step_size"] for trial in trials] != list(SEARCH_VALUES):
        raise RuntimeError("completed trials do not match the declared search space")
    best = min(trials, key=lambda trial: trial["loss"])
    if best["step_size"] != 0.2 or best["loss"] != 0.0:
        raise RuntimeError("synthetic search did not recover the known optimum")
    return _summary_record(trials, best, experiment_path)


def _trial_record(result: Any) -> dict[str, Any]:
    """Normalize one native Tune result without infrastructure identifiers."""
    metrics = result.metrics
    record = {
        "step_size": result.config["step_size"],
        "loss": metrics["loss"],
        "iterations": metrics["iteration"],
        "resumed": metrics["resumed"],
        "checkpoint_available": result.checkpoint is not None,
    }
    if record["step_size"] not in SEARCH_VALUES:
        raise RuntimeError("trial reported an undeclared search value")
    if not isinstance(record["loss"], (int, float)) or not math.isfinite(record["loss"]):
        raise RuntimeError("trial reported a non-finite loss")
    if record["iterations"] != 3 or type(record["resumed"]) is not bool:
        raise RuntimeError("trial completion metrics are invalid")
    if not record["checkpoint_available"]:
        raise RuntimeError("trial completed without its final checkpoint")
    return record


def _summary_record(
    trials: list[dict[str, Any]], best: dict[str, Any], path: str
) -> dict[str, Any]:
    """Create the stable application result record."""
    return {
        "status": "succeeded",
        "ray_version": "2.58.0",
        "experiment_path": path,
        "trial_count": len(trials),
        "best_step_size": best["step_size"],
        "best_loss": best["loss"],
        "trials": trials,
    }


def _experiment_path(storage_path: str, run_name: str) -> str:
    """Resolve the exact path consumed by ``Tuner.restore``."""
    return normalize_storage_path(storage_path).rstrip("/") + "/" + run_name


def normalize_storage_path(storage_path: str) -> str:
    """Convert a local path to the absolute form required by Arrow.

    Args:
        storage_path: Local directory or remote filesystem URI.
    Returns:
        Unchanged remote URI or absolute local path.
    Raises:
        ValueError: The storage path is empty.
    """
    if not storage_path:
        raise ValueError("storage-path must not be empty")
    if "://" in storage_path:
        target = urlsplit(storage_path)
        parts = target.path.strip("/").split("/")
        invalid = (
            target.scheme != "s3"
            or not target.netloc
            or target.username
            or target.password
            or target.query
            or target.fragment
            or not target.path.strip("/")
            or any(part in ("", ".", "..") for part in parts)
        )
        if invalid:
            raise ValueError("storage-path must be a run-scoped unsigned s3:// URI")
        return storage_path
    return str(Path(storage_path).expanduser().resolve())


def _build_tuner(settings: dict[str, Any], storage_path: str, run_name: str, restore: bool):
    """Build or restore the native Tuner for one immutable recipe."""
    from ray import tune

    trainable = tune.with_resources(objective, resources={"cpu": 1})
    storage_path = normalize_storage_path(storage_path)
    experiment_path = _experiment_path(storage_path, run_name)
    if restore:
        if not tune.Tuner.can_restore(experiment_path):
            raise ValueError("no restorable Tune experiment exists at the requested path")
        return tune.Tuner.restore(experiment_path, trainable=trainable, resume_errored=True)
    parameter_space = {**settings, "step_size": tune.grid_search(list(SEARCH_VALUES))}
    return tune.Tuner(
        trainable,
        param_space=parameter_space,
        tune_config=tune.TuneConfig(metric="loss", mode="min"),
        run_config=tune.RunConfig(
            name=run_name,
            storage_path=storage_path,
            failure_config=tune.FailureConfig(max_failures=1),
            checkpoint_config=tune.CheckpointConfig(
                num_to_keep=1,
                checkpoint_score_attribute="loss",
                checkpoint_score_order="min",
            ),
        ),
    )


def _write_json(path: Path, value: Any) -> None:
    """Write stable private JSON bytes."""
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")
    path.chmod(0o600)


def _export(output_dir: Path, summary: dict[str, Any]) -> None:
    """Write a fresh checksum-bound result directory."""
    output_dir.mkdir(parents=True, exist_ok=False, mode=0o700)
    result_summary = summary.copy()
    trials = result_summary.pop("trials")
    _write_json(output_dir / "result.json", result_summary)
    _write_json(output_dir / "trials.json", trials)
    source_digest = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
    runtime = {
        "python": sys.version.split()[0],
        "ray": "2.58.0",
        "source_sha256": source_digest,
    }
    _write_json(output_dir / "runtime.json", runtime)
    lines = []
    for name in ARTIFACT_NAMES:
        digest = hashlib.sha256((output_dir / name).read_bytes()).hexdigest()
        lines.append(f"{digest}  {name}\n")
    (output_dir / "SHA256SUMS").write_text("".join(lines))
    (output_dir / "SHA256SUMS").chmod(0o600)


def _parse_args() -> argparse.Namespace:
    """Parse the standalone native Jobs application arguments."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--storage-path", required=True)
    parser.add_argument("--run-name", required=True)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--fail-step-size", type=float)
    parser.add_argument("--restore", action="store_true")
    parser.add_argument("--local", action="store_true")
    return parser.parse_args()


def _initialize_ray(local: bool):
    """Verify and connect to the selected application Ray runtime."""
    import ray

    if ray.__version__ != "2.58.0":
        raise RuntimeError("This reference requires Ray 2.58.0")
    if local:
        ray.init(num_cpus=2)
    else:
        ray.init(address="auto")
    return ray


def _fit_and_export(arguments: argparse.Namespace, settings: dict[str, Any]) -> dict[str, Any]:
    """Fit or restore the Tune experiment and export its validated result."""
    tuner = _build_tuner(
        settings, arguments.storage_path, arguments.run_name, arguments.restore
    )
    results = tuner.fit()
    summary = summarize(results, results.experiment_path)
    _export(arguments.output_dir.resolve(), summary)
    return summary


def main() -> None:
    """Run Tune and emit a checksum-bound result summary.

    Args:
        None.
    Returns:
        None.
    Raises:
        RuntimeError: Ray or Tune did not produce the declared result.
        ValueError: Search settings or recovery state are invalid.
        OSError: Artifact output cannot be created.
    """
    arguments = _parse_args()
    settings = {
        "iterations": 3,
        "target": 0.2,
        "fail_value": arguments.fail_step_size,
    }
    validate_settings(settings)
    validate_run_name(arguments.run_name)
    os.umask(0o077)
    ray = _initialize_ray(arguments.local)
    try:
        summary = _fit_and_export(arguments, settings)
    finally:
        ray.shutdown()
    receipt_keys = ("status", "trial_count", "best_step_size", "best_loss")
    receipt = {key: summary[key] for key in receipt_keys}
    receipt["output_dir"] = str(arguments.output_dir.resolve())
    print(json.dumps(receipt, sort_keys=True))


if __name__ == "__main__":
    main()
