"""Complete interrupted reference reports while refusing different retained bytes."""

from npa.clients.storage import StoragePreconditionFailed
from npa.workflows.field_failure.artifacts import _encode, _location, _storage


def publish_record(uri, payload):
    """Publish a reference selection or result, accepting an identical prior write.

    Args:
        uri: Exact run-scoped reference selection or result object URI.
        payload: Recomputed selection or report from unchanged measured inputs.
    Returns:
        None after a successful write or an exact retained-byte match.
    Raises:
        ValueError: The destination is invalid or its retained bytes differ.
        StorageError: Publication or exact readback fails.
    """
    _publish_exact(uri, _encode(payload), "application/json")


def publish_html(uri, contents):
    """Publish reference HTML without overwriting an existing different report.

    Args:
        uri: Exact run-scoped report object URI.
        contents: Regenerated standalone HTML from the same measured inputs.
    Returns:
        None after a successful write or an exact retained-byte match.
    Raises:
        ValueError: The destination is invalid or its retained bytes differ.
        StorageError: Publication or exact readback fails.
    """
    _publish_exact(uri, contents.encode(), "text/html; charset=utf-8")


def _publish_exact(uri, data, content_type):
    _location(uri)
    storage = _storage()
    try:
        storage.put_bytes_conditional(
            data, uri, if_none_match=True, content_type=content_type
        )
    except StoragePreconditionFailed:
        retained = storage.read_bytes_with_etag(uri)
        if retained is None or retained[0] != data:
            raise ValueError(
                "retained reference publication differs from regenerated bytes"
            ) from None
