"""Render a solutions-library ``terraform.tfvars`` from a :class:`SoperatorSpec`.

The solutions-library recipe defaults to a 128x H100 production cluster, so
every nodeset must be set explicitly. This renderer produces a minimal, working
tfvars: a trimmed control plane, one worker nodeset per spec pool (mixed presets
supported), optional per-pool node-local Docker/Enroot image cache
(``NETWORK_SSD_IO_M3``), NFS-in-k8s, accounting/telemetry/backups off by
default, and ``use_default_apparmor_profile`` wired from the spec.
"""

from __future__ import annotations

from npa.soperator.spec import SoperatorSpec, WorkerPoolSpec


def _bool(value: bool) -> str:
    return "true" if value else "false"


def _render_worker(pool: WorkerPoolSpec) -> str:
    lines: list[str] = []
    lines.append("  {")
    lines.append(f'    name = "{pool.name}"')
    lines.append(f"    size = {pool.size}")
    lines.append("    autoscaling = {")
    lines.append("      enabled = false")
    lines.append("    }")
    lines.append("    resource = {")
    lines.append(f'      platform = "{pool.platform}"')
    lines.append(f'      preset   = "{pool.preset}"')
    lines.append("    }")
    lines.append("    boot_disk = {")
    lines.append('      type                 = "NETWORK_SSD"')
    lines.append(f"      size_gibibytes       = {pool.boot_disk_gib}")
    lines.append("      block_size_kibibytes = 4")
    lines.append("    }")
    if pool.is_gpu():
        lines.append("    gpu_cluster = {")
        lines.append(f'      infiniband_fabric = "{pool.fabric}"')
        lines.append("    }")
    lines.append(f"    preemptible = {'{}' if pool.preemptible else 'null'}")
    lines.append("    features = null")
    lines.append("    create_partition = null")
    lines.append("    ephemeral_nodes                = false")
    lines.append("    initial_number_ephemeral_nodes = 0")
    lines.append("    persistent_volume_claim_retention_policy = {")
    lines.append('      when_deleted = "Delete"')
    lines.append('      when_scaled  = "Delete"')
    lines.append("    }")
    lines.append("    max_pods = 32")
    lines.append("    node_local_jail_submounts = []")
    if pool.docker_cache:
        # Node-local Docker/Enroot image cache disk (IO_M3 by default).
        lines.append("    node_local_image_disk = {")
        lines.append("      enabled = true")
        lines.append("      spec = {")
        lines.append(f"        size_gibibytes  = {pool.docker_cache_gib}")
        lines.append('        filesystem_type = "ext4"')
        lines.append(f'        disk_type       = "{pool.docker_cache_disk_type}"')
        lines.append("      }")
        lines.append("    }")
    else:
        lines.append("    node_local_image_disk = {")
        lines.append("      enabled = false")
        lines.append("    }")
    lines.append("  },")
    return "\n".join(lines)


def render_tfvars(spec: SoperatorSpec) -> str:
    """Return the full ``terraform.tfvars`` content for *spec*."""

    workers_block = "\n".join(_render_worker(p) for p in spec.workers)
    ssh_keys = "\n".join(f'  "{key}",' for key in spec.ssh_public_keys)
    telemetry = _bool(spec.telemetry)
    # ActiveChecks in the "dev" scope run NCCL all-reduce + InfiniBand + GPU perf
    # jobs that Error on a CPU-only cluster, hanging wait_for_soperator_activechecks_hr
    # (so terraform apply never returns). The recipe requires a valid scope
    # (variables.tf validation rejects ""), so on CPU-only clusters use "essential",
    # which sets runAfterCreation=false for every GPU/NCCL/IB/perf check and only
    # runs CPU-safe checks (ssh-check, etc.).
    active_checks_scope = "dev" if any(p.is_gpu() for p in spec.workers) else "essential"
    # filestore_accounting must be non-null only when accounting is enabled, but
    # slurm_nodeset_accounting's variable validation dereferences it even when
    # disabled -- so always provide a valid accounting nodeset object.
    filestore_accounting = (
        "filestore_accounting = {\n"
        "  spec = {\n"
        "    size_gibibytes       = 512\n"
        "    block_size_kibibytes = 4\n"
        "    forbid_deletion      = false\n"
        "  }\n"
        "}"
        if spec.accounting
        else "filestore_accounting = null"
    )

    return f"""# Generated by `npa soperator deploy` from an npa.soperator/v0.0.1 spec.
# Cluster: {spec.name}
company_name = "{spec.name}"
production   = false

# --- Storage ---
controller_state_on_filestore = false
filestore_controller_spool = {{
  spec = {{
    size_gibibytes       = 128
    block_size_kibibytes = 4
    forbid_deletion      = false
  }}
}}
filestore_jail = {{
  spec = {{
    size_gibibytes       = {spec.jail_size_gib}
    block_size_kibibytes = 4
    forbid_deletion      = false
  }}
}}
filestore_jail_submounts   = []
allow_empty_jail_submounts = true
{filestore_accounting}

nfs_in_k8s = {{
  enabled         = true
  version         = "1.2.0"
  use_stable_repo = true
  size_gibibytes  = 186
  disk_type       = "NETWORK_SSD_IO_M3"
  filesystem_type = "ext4"
  threads         = 8
}}

# --- Slurm ---
slurm_operator_version = "{spec.slurm_operator_version}"
slurm_operator_stable  = true

slurm_nodesets_partitions = [
  {{
    name               = "main"
    is_all             = true
    slurm_nodeset_refs = []
    config             = "Default=YES PriorityTier=10 PreemptMode=OFF MaxTime=INFINITE State=UP OverSubscribe=YES"
  }},
  {{
    name               = "hidden"
    is_all             = true
    slurm_nodeset_refs = []
    config             = "Default=NO PriorityTier=10 PreemptMode=OFF Hidden=YES MaxTime=INFINITE State=UP OverSubscribe=YES"
  }},
]
slurm_partition_config_type = "default"

# --- Nodes ---
slurm_nodeset_system = {{
  min_size = {spec.system_min_size}
  max_size = {spec.system_min_size}
  resource = {{
    platform = "cpu-d3"
    preset   = "{spec.system_preset}"
  }}
  boot_disk = {{
    type                 = "NETWORK_SSD"
    size_gibibytes       = 128
    block_size_kibibytes = 4
  }}
}}

# Trimmed so the operator stack fits small (>=8vcpu) system nodes.
system_resources = {{
  rest = {{
    cpu_cores                   = 3
    memory_gibibytes            = 8
    ephemeral_storage_gibibytes = 5
  }}
  exporter = {{
    cpu_cores                   = 1
    memory_gibibytes            = 4
    ephemeral_storage_gibibytes = 2
  }}
  mariadb = {{
    cpu_cores                   = 2
    memory_gibibytes            = 6
    ephemeral_storage_gibibytes = 32
  }}
  node_configurator = {{
    requests = {{ cpu_cores = 0.5, memory_gibibytes = 0.25 }}
    limits   = {{ memory_gibibytes = 0.25 }}
  }}
  slurm_operator = {{
    requests = {{ cpu_cores = 1, memory_gibibytes = 4 }}
    limits   = {{ memory_gibibytes = 4 }}
  }}
  slurm_checks = {{
    requests = {{ cpu_cores = 1, memory_gibibytes = 4 }}
    limits   = {{ memory_gibibytes = 4 }}
  }}
  kruise_daemon = {{ cpu_cores = 1, memory_gibibytes = 4 }}
  dcgm_exporter = {{ cpu_cores = 0.05, memory_gibibytes = 0.5 }}
}}

slurm_nodeset_controller = {{
  size = 1
  resource = {{
    platform = "cpu-d3"
    preset   = "{spec.controller_preset}"
  }}
  boot_disk = {{
    type                 = "NETWORK_SSD"
    size_gibibytes       = 128
    block_size_kibibytes = 4
  }}
}}

slurm_nodeset_workers = [
{workers_block}
]

use_preinstalled_gpu_drivers = true

slurm_nodeset_login = {{
  size = 1
  resource = {{
    platform = "cpu-d3"
    preset   = "{spec.login_preset}"
  }}
  boot_disk = {{
    type                 = "NETWORK_SSD"
    size_gibibytes       = 256
    block_size_kibibytes = 4
  }}
}}

# accounting_enabled gates whether this nodeset creates an instance; the object
# is required for variable validation regardless.
slurm_nodeset_accounting = {{
  resource = {{
    platform = "cpu-d3"
    preset   = "16vcpu-64gb"
  }}
  boot_disk = {{
    type                 = "NETWORK_SSD"
    size_gibibytes       = 128
    block_size_kibibytes = 4
  }}
}}

slurm_nodeset_nfs = null

slurm_login_public_ip = true
slurm_login_ssh_root_public_keys = [
{ssh_keys}
]

slurm_exporter_enabled = {_bool(spec.telemetry)}
active_checks_scope    = "{active_checks_scope}"
slurm_shared_memory_size_gibibytes = 16
slurm_topology_block_size = null
maintenance_ignore_node_groups = ["controller", "nfs"]

telemetry_enabled        = {telemetry}
public_o11y_enabled      = {telemetry}
dcgm_job_mapping_enabled = {telemetry}
opentelemetry_delete_jail_logs_after_read = false
soperator_notifier   = {{ enabled = false }}
nccl_inspector_profiling = {{ enabled = false }}

accounting_enabled = {_bool(spec.accounting)}

backups_enabled           = "force_disable"
backups_password          = "unused-backups-disabled"
backups_schedule          = "@daily-random"
backups_prune_schedule    = "@daily-random"
backups_retention         = {{ keepDaily = 7 }}
cleanup_bucket_on_destroy = false

k8s_version = 1.33
nvidia_config_lines = [
  "options nvidia NVreg_RestrictProfilingToAdminUsers=0",
  "options nvidia NVreg_EnableStreamMemOPs=1",
]

# Custom localhost AppArmor profile is not loaded by SPO in 4.1.0-stable; use
# unconfined so login/worker sshd start. Overridable via the spec.
use_default_apparmor_profile = {_bool(spec.use_default_apparmor_profile)}
"""
