# Generated by `npa fleet` -- a single k8s-training cluster in one project.
# The k8s-training module source and provider domain are substituted at deploy
# time; per-cluster values live in terraform.tfvars, and tenant/project/region/
# iam_token/ssh come from TF_VAR_* env at apply time.

terraform {
  required_version = ">= 1.3"

  required_providers {
    nebius = {
      source  = "terraform-provider.storage.eu-north1.nebius.cloud/nebius/nebius"
      version = "~> 0.5.201"
    }
  }
}

provider "nebius" {
  domain = "__PROVIDER_DOMAIN__"
  token  = var.iam_token
}

locals {
  create_subnet = trimspace(var.subnet_id) == ""
  subnet_id     = local.create_subnet ? nebius_vpc_v1_subnet.cluster[0].id : var.subnet_id
  infiniband_fabric = trimspace(var.infiniband_fabric) == "" ? null : var.infiniband_fabric
}

resource "nebius_vpc_v1_network" "cluster" {
  count     = local.create_subnet ? 1 : 0
  parent_id = var.parent_id
  name      = "${var.cluster_name}-network"
}

resource "nebius_vpc_v1_subnet" "cluster" {
  count      = local.create_subnet ? 1 : 0
  parent_id  = var.parent_id
  network_id = nebius_vpc_v1_network.cluster[0].id
  name       = "${var.cluster_name}-subnet"
}

module "k8s_training" {
  source = "__K8S_TRAINING_SOURCE__"

  tenant_id = var.tenant_id
  parent_id = var.parent_id
  region    = var.region
  subnet_id = local.subnet_id
  iam_token = var.iam_token

  cluster_name                 = var.cluster_name
  k8s_version                  = var.k8s_version
  ssh_public_key               = { key = var.ssh_public_key }
  mk8s_cluster_public_endpoint = true
  enable_k8s_node_group_sa     = false
  enable_egress_gateway        = false

  cpu_nodes_public_ips  = false
  gpu_nodes_public_ips  = false
  cpu_nodes_preemptible = false
  gpu_nodes_preemptible = false

  cpu_nodes_fixed_count = var.cpu_nodes_count
  cpu_nodes_platform    = var.cpu_nodes_platform
  cpu_nodes_preset      = var.cpu_nodes_preset

  gpu_nodes_fixed_count_per_group = var.gpu_nodes_count
  gpu_node_groups                 = var.gpu_nodes_count > 0 ? 1 : 0
  gpu_nodes_platform              = var.gpu_nodes_platform
  gpu_nodes_preset                = var.gpu_nodes_preset
  gpu_disk_size                   = var.gpu_disk_size
  gpu_nodes_driverfull_image      = false
  enable_gpu_cluster              = var.enable_gpu_cluster
  infiniband_fabric               = local.infiniband_fabric
  custom_driver                   = false
  mig_strategy                    = "none"

  enable_filestore              = var.enable_filestore
  existing_filestore            = var.existing_filestore
  filestore_disk_size_gibibytes = var.filestore_disk_size_gibibytes
  filesystem_csi = {
    chart_version                       = "0.1.5"
    namespace                           = "kube-system"
    make_default_storage_class          = true
    previous_default_storage_class_name = "compute-csi-default-sc"
  }

  # Keep the fleet cheap and quiet: no observability/logging/ray/gatekeeper.
  enable_nebius_o11y_agent = false
  enable_grafana           = false
  enable_prometheus        = false
  collectK8sClusterMetrics = false
  loki = {
    enabled            = false
    replication_factor = 1
  }
  enable_kuberay_cluster = false
  enable_kuberay_service = false
  enable_opa_gatekeeper  = false
}

output "kube_cluster" {
  description = "Managed Kubernetes cluster information."
  value       = module.k8s_training.kube_cluster
}

output "created_subnet_id" {
  description = "Subnet created by this wrapper when subnet_id was empty."
  value       = local.create_subnet ? nebius_vpc_v1_subnet.cluster[0].id : null
}
