"""Present real NuRec capture, reconstruction and novel-view outputs as offline HTML."""

from __future__ import annotations

import math
import json
from pathlib import Path

from PIL import Image

from npa.workflows.preview_html import image_preview, write_preview


def _images(root: Path) -> list[Path]:
    return sorted(
        path
        for path in root.rglob("*")
        if path.is_file() and path.suffix.lower() in {".png", ".jpg", ".jpeg"}
    )


def _group(title: str, images: list[Path], note: str) -> dict:
    count = min(len(images), 32)
    indices = [
        round(index * (len(images) - 1) / max(1, count - 1)) for index in range(count)
    ]
    frames = []
    for index in indices:
        with Image.open(images[index]) as image:
            frames.append(
                {
                    "label": f"Image {index + 1} of {len(images)}",
                    "images": [
                        {"label": title, "data": image_preview(image, width=960)}
                    ],
                }
            )
    return {"title": title, "note": note, "frames": frames}


def _quality(path: Path) -> dict:
    from npa.workbench.nurec.nurec import parse_metrics_yaml

    # Use the native parser so aggregated NRE 26.04 values and earlier flat
    # metrics have the same meaning in the report and reconstruction result.
    values = {
        name: round(value, 6)
        for name, value in parse_metrics_yaml(path).items()
        if name in {"test/psnr", "test/ssim", "test/lpips"} and math.isfinite(value)
    }
    return values or {"NRE quality metrics": "unavailable"}


def _timelines(capture, novel, validation, validation_root, view_type="Novel views"):
    groups = [
        _group(
            view_type,
            novel,
            "NRE renders from a nonzero rig offset. These views are not paired with source image indices."
            if view_type == "Novel views"
            else "NRE renders at the recorded training viewpoints.",
        ),
        _group(
            "Input capture",
            capture,
            "Photographic source frames exported from the selected NCore capture.",
        ),
    ]
    groups.extend(_validation_timelines(validation, validation_root))
    return groups


def _validation_timelines(images, root):
    modalities = {
        "pred_rgb": "Predicted RGB",
        "pred_distance": "Predicted distance",
        "pred_opacity": "Predicted opacity",
    }
    grouped = {
        title: [] for title in [*modalities.values(), "Unclassified validation output"]
    }
    for path in images:
        modality = path.relative_to(root).parts[0]
        title = modalities.get(modality, "Unclassified validation output")
        grouped[title].append(path)
    return [
        _group(
            "Reconstruction validation · " + title,
            paths,
            "NRE validation outputs grouped by their recorded modality. Distance and opacity are diagnostic visualizations, not RGB photographs. Quality measurements come from NRE validation, not from the novel-view slideshow.",
        )
        for title, paths in grouped.items()
        if paths
    ]


def _public_sample_credit(root):
    from npa.workbench.nurec.nurec import (
        DEFAULT_DATASET_ID,
        DEFAULT_DATASET_REVISION,
    )

    path = root / "ncore" / "manifest.json"
    if not path.is_file():
        return None
    manifest = json.loads(path.read_text())
    if (
        manifest.get("dataset_id") != DEFAULT_DATASET_ID
        or manifest.get("dataset_revision") != DEFAULT_DATASET_REVISION
    ):
        return None
    source = f"https://huggingface.co/datasets/{DEFAULT_DATASET_ID}"
    return {
        "public_sample": {
            "creator": "NVIDIA",
            "source": source + "/tree/" + DEFAULT_DATASET_REVISION,
            "license": "Creative Commons Attribution 4.0 International",
            "license_url": "https://creativecommons.org/licenses/by/4.0/",
            "modifications": "Source images are resized and JPEG encoded for display. Reconstruction and novel views are generated by NRE.",
        }
    }


def write_nurec_preview(root: Path, output: Path) -> dict:
    """Build independent visual timelines from actual NuRec outputs.

    Args:
        root: Materialized canonical run directory.
        output: Local destination for the self-contained HTML preview.

    Returns:
        Actual image counts and presentation sampling scope.

    Raises:
        ValueError: Capture frames or novel renders are missing.
        OSError: An output image cannot be read.
    """
    capture = _images(root / "input")
    novel = _images(root / "novel_views")
    validation = _images(root / "reconstruction" / "val")
    if not capture or not novel:
        raise ValueError("NuRec preview requires actual capture and novel-view images")
    counts = {
        "capture images": len(capture),
        "novel views": len(novel),
        "validation images": len(validation),
    }
    write_preview(output, **_presentation(root, capture, novel, validation, counts))
    return {"image_counts": counts, "maximum_preview_images_per_group": 32}


def _presentation(root, capture, novel, validation, counts):
    from npa.workbench.nurec.render_evidence import verified_render_summary

    evidence = verified_render_summary(root)
    hardware = {"render GPU": evidence.get("render GPU", "Unverified")}
    return dict(
        title="Digital twin · neural reconstruction",
        metrics={
            **{
                ("rendered views" if key == "novel views" else key): value
                for key, value in counts.items()
            },
            **hardware,
            **_quality(root / "reconstruction" / "metrics.yaml"),
        },
        summary="Explore a reconstructed real-world scene. Scrub or play the recorded camera views below. Each timeline samples up to 32 actual NRE output images; playback is a slideshow, not live free-camera rendering. Gaussian appearance alone does not establish collision geometry or navigation readiness.",
        groups=_timelines(
            capture,
            novel,
            validation,
            root / "reconstruction" / "val",
            evidence.get("view type", "Novel views"),
        ),
        details={**(_public_sample_credit(root) or {}), "render_evidence": evidence},
    )
